- hosts: master 
  remote_user: root
  vars_files:
   - vars/user.yml
   - vars/var_basic.yml
   - vars/var_master.yml
  vars:
     add_user: true
     generate_key: true
     open_firewall: true
     disable_firewall: false
     install_hadoop: true
     config_hadoop: true
  roles:
    #- create_user p[create user will done during keyless]
    - user
    - fetch_public_key
    - authorized
    - download_hadoop_targz
    #- java  [this is open jdk java]
    - hadoop
